name: Koyeb Action
description: Install and configure the Koyeb CLI so you can deploy and manage your apps on Koyeb.
inputs:
  api_token:
    description: 'Koyeb API token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Koyeb CLI
      run: |
        set -x
        mkdir ${{github.action_path}}/bin
        curl -sL -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' $(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/koyeb/koyeb-cli/releases/latest \
          | grep 'http.*koyeb-cli_.*_linux_amd64' \
          | awk '{print $2}' \
          | sed 's|[\"\,]*||g') | tar xvz -C ${{github.action_path}}/bin/
        chmod +x ${{github.action_path}}/bin/koyeb
        echo ${{github.action_path}}/bin/ >> $GITHUB_PATH
      shell: bash
    - name: Configure Koyeb CLI
      shell: bash
      run: |
        set -x
        echo "token: $KOYEB_API_KEY" > ~/.koyeb.yaml
      env:
        KOYEB_API_KEY: ${{inputs.api_token}}
