name: Koyeb Action
description: Install and configure the Koyeb CLI so you can deploy and manage your apps on Koyeb.

inputs:
  api_token:
    description: "Koyeb API token"
    required: true

  github_token:
    description: "Github API token"
    default: ${{ github.token }}
    required: true

runs:
  using: "composite"
  steps:
    - name: Check if Koyeb CLI is already installed
      id: check-koyeb-cli-installed
      shell: bash
      run: |
        set -eo pipefail

        bin_dir="${{ github.action_path }}/bin"
        is_installed=$(test -f "$bin_dir/koyeb" && echo true || echo false)

        if [ "$is_installed" = 'true' ]; then
          echo "Koyeb CLI already installed, skip installation"
        fi

        echo "bin-dir=$bin_dir" >> "$GITHUB_OUTPUT"
        echo "is-installed=$is_installed" >> "$GITHUB_OUTPUT"

    - name: Retrieve Koyeb CLI URL
      id: retrieve-koyeb-cli-url
      if: ${{ steps.check-koyeb-cli-installed.outputs.is-installed == 'false' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        set -eo pipefail

        releases=$(curl -si -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/koyeb/koyeb-cli/releases/latest)
        latest_release_url=$(echo "$releases" | grep 'http.*koyeb-cli_.*_linux_amd64' | awk '{print $2}' | sed 's|[\"\,]*||g')

        if [ -z "$latest_release_url" ]; then
          echo "Cannot find latest Koyeb CLI release URL"
          echo "$releases"
          exit 1
        fi

        echo "koyeb-cli-url=$latest_release_url" >> "$GITHUB_OUTPUT"

    - name: Download and Install Koyeb CLI
      if: ${{ steps.check-koyeb-cli-installed.outputs.is-installed == 'false' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        KOYEB_CLI_BIN_DIR: ${{ steps.check-koyeb-cli-installed.outputs.bin-dir }}
        KOYEB_CLI_URL: ${{ steps.retrieve-koyeb-cli-url.outputs.koyeb-cli-url }}
      run: |
        set -eo pipefail

        bin_dir="$KOYEB_CLI_BIN_DIR"
        mkdir "$bin_dir"

        curl -sL -H "Authorization: Bearer $GITHUB_TOKEN" "$KOYEB_CLI_URL" | tar xvz -C "$bin_dir"
        chmod +x "$bin_dir/koyeb"
        echo "$bin_dir" >> "$GITHUB_PATH"

    - name: Configure Koyeb CLI
      if: ${{ steps.check-koyeb-cli-installed.outputs.is-installed == 'false' }}
      shell: bash
      env:
        KOYEB_API_KEY: ${{inputs.api_token}}
      run: |
        echo "token: $KOYEB_API_KEY" > ~/.koyeb.yaml
